# Generated by Django 3.1.4 on 2020-12-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_leaveapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='description',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='reason',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('declined', 'declined'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
