# Generated by Django 3.1.4 on 2020-12-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20201225_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'approved'), ('declined', 'declined'), ('pending', 'pending')], max_length=20)),
                ('leaveapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.leaveapplication')),
            ],
        ),
    ]
