# Generated by Django 3.1.4 on 2020-12-25 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0007_appresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appresponse',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('pending', 'pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('pending', 'pending')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='AllLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
